import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8080/api';
const voterID = (() => { const key='livepoll-voter-id'; let id=localStorage.getItem(key); if(!id){ id=crypto.randomUUID(); localStorage.setItem(key,id); } return id; })();
const request = async (path, options={}) => {
  const token=localStorage.getItem('livepoll-token');
  const response=await fetch(`${API}${path}`, {...options, headers:{'Content-Type':'application/json', ...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});
  const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error||'Something went wrong.'); return data;
};
const total = poll => poll.options.reduce((sum,o)=>sum+o.votes,0);
function Auth({onDone}) { const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false); const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await request(`/auth/${mode==='login'?'login':'signup'}`,{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('livepoll-token',r.token);localStorage.setItem('livepoll-email',r.email);onDone();}catch(e){setError(e.message)}finally{setBusy(false)}};return <main className="center"><section className="card auth"><span className="eyebrow">LIVEPOLL</span><h1>Make every vote visible.</h1><p>Create a poll, share one neat link, and watch the room decide together.</p><form onSubmit={submit}><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input required minLength="8" maxLength="72" type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?'Just a second…':mode==='login'?'Log in':'Create account'}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Need an account? Sign up':'Already have an account? Log in'}</button></section></main> }
function CreatePoll({onCreated}) { const [title,setTitle]=useState(''),[choices,setChoices]=useState(['','']),[error,setError]=useState(''),[busy,setBusy]=useState(false); const change=(i,v)=>setChoices(choices.map((x,n)=>n===i?v:x)); const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{onCreated(await request('/polls',{method:'POST',body:JSON.stringify({title,options:choices})}));setTitle('');setChoices(['','']);}catch(e){setError(e.message)}finally{setBusy(false)}};return <section className="card create"><div><span className="eyebrow">NEW POLL</span><h2>Ask a great question.</h2></div><form onSubmit={submit}><label>Your question<input maxLength="140" required placeholder="Where should we go for lunch?" value={title} onChange={e=>setTitle(e.target.value)} /></label><div className="choices">{choices.map((choice,i)=><label key={i}>Choice {i+1}<span className="choice-row"><input maxLength="80" required value={choice} onChange={e=>change(i,e.target.value)} placeholder={`Option ${i+1}`} />{choices.length>2&&<button type="button" className="remove" onClick={()=>setChoices(choices.filter((_,n)=>n!==i))}>×</button>}</span></label>)}</div>{choices.length<8&&<button className="add" type="button" onClick={()=>setChoices([...choices,''])}>+ Add choice</button>}{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?'Creating…':'Create poll'}</button></form></section> }
function Results({poll, canVote=false, onVoted}) { const [selected,setSelected]=useState(''),[message,setMessage]=useState(''),[voted,setVoted]=useState(false); const count=total(poll); const vote=async()=>{if(!selected)return setMessage('Pick an option first.');try{await request(`/polls/${poll.id}/votes`,{method:'POST',headers:{'X-Voter-ID':voterID},body:JSON.stringify({optionId:selected})});setVoted(true);setMessage('Vote counted — results are live.');onVoted?.()}catch(e){setVoted(true);setMessage(e.message)}};return <section className="card poll"><div className="poll-heading"><div><span className="eyebrow">{count} {count===1?'VOTE':'VOTES'} · LIVE</span><h1>{poll.title}</h1></div><i className="live-dot" title="Live updates connected" /></div><div className="answers">{poll.options.map(option=>{const percent=count?Math.round(option.votes/count*100):0;return <div className="answer" key={option.id}><button className={selected===option.id?'selected':''} disabled={!canVote||voted} onClick={()=>setSelected(option.id)}><span className="radio" />{option.label}</button><div className="bar"><span style={{width:`${percent}%`}} /></div><strong>{option.votes} <small>{percent}%</small></strong></div>})}</div>{canVote&&!voted&&<button onClick={vote}>Cast your vote</button>}{message&&<p className={message.includes('counted')?'success':'error'}>{message}</p>}</section> }
function PollPage({id}) { const [poll,setPoll]=useState(null),[error,setError]=useState(''); const load=()=>request(`/polls/${id}`).then(setPoll).catch(e=>setError(e.message)); useEffect(()=>{load();const source=new EventSource(`${API}/polls/${id}/events`);source.addEventListener('results',e=>{const counts=JSON.parse(e.data);setPoll(current=>current?{...current,options:current.options.map(o=>({...o,votes:counts[o.id]??o.votes}))}:current)});return()=>source.close()},[id]);if(error)return <main className="center"><p className="error">{error}</p></main>;if(!poll)return <main className="center">Loading this poll…</main>;return <main className="center"><Results poll={poll} canVote onVoted={load}/><p className="hint">Results update automatically for everyone watching.</p></main> }
function Dashboard() { const [polls,setPolls]=useState([]),[created,setCreated]=useState(null),[copied,setCopied]=useState(false); const load=()=>request('/mine').then(setPolls).catch(()=>{});useEffect(load,[]);const share=async p=>{await navigator.clipboard.writeText(`${location.origin}/p/${p.id}`);setCreated(p);setCopied(true);setTimeout(()=>setCopied(false),1800)};return <main><header><a className="logo" href="/">LIVEPOLL</a><div>{localStorage.getItem('livepoll-email')} <button className="link" onClick={()=>{localStorage.clear();location.reload()}}>Log out</button></div></header><div className="dashboard"><CreatePoll onCreated={p=>{setPolls([p,...polls]);setCreated(p);share(p)}}/><section className="my-polls"><span className="eyebrow">YOUR POLLS</span><h2>Share the room.</h2>{created&&<div className="share"><span>{copied?'Link copied!':'Your poll is ready.'}</span><a href={`/p/${created.id}`}>{location.origin}/p/{created.id}</a><button onClick={()=>share(created)}>Copy link</button></div>}{polls.length===0?<p className="muted">Your first poll will appear here.</p>:polls.map(p=><article className="poll-item" key={p.id}><div><b>{p.title}</b><span>{total(p)} votes</span></div><a href={`/p/${p.id}`}>Open →</a><button className="link" onClick={()=>share(p)}>Copy link</button></article>)}</section></div></main> }
function App(){ const poll=location.pathname.match(/^\/p\/([a-f\d]{24})$/i); if(poll)return <PollPage id={poll[1]}/>; const [ready,setReady]=useState(!!localStorage.getItem('livepoll-token'));return ready?<Dashboard/>:<Auth onDone={()=>setReady(true)}/> }
createRoot(document.getElementById('root')).render(<App/>);
